version: "3.8"

services: 
    
  php:
    build:
      context: './php/'
      args: 
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./app/:/var/www/vhosts/app/:rw
      - ./php/conf/ambiente.ini:/usr/local/etc/php/conf.d/ambiente.ini
    container_name: SRV_${PHP_CONTAINER_NAME}${PHP_VERSION}
    
  apache:
    build:
      context: './apache/'
      args: 
        APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
    ports:
      - ${APACHE_PORT}:80
    volumes:
      - ./app/:/var/www/vhosts/app/:rw
      - ./apache/logs/:/var/log/apache2/
    container_name: SRV_${APACHE_CONTAINER_NAME}${APACHE_VERSION}